# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/innovril/vivado1/1_adder/1_adder/1_adder.cache/wt [current_project]
set_property parent.project_path /home/innovril/vivado1/1_adder/1_adder/1_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/innovril/vivado1/lcd_module.dcp
set_property used_in_implementation false [get_files /home/innovril/vivado1/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  /home/innovril/vivado1/1_adder/adder.v
  /home/innovril/vivado1/1_adder/adder_display.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/innovril/vivado1/1_adder/adder.xdc
set_property used_in_implementation false [get_files /home/innovril/vivado1/1_adder/adder.xdc]


synth_design -top adder_display -part xc7a200tfbg676-2


write_checkpoint -force -noxdef adder_display.dcp

catch { report_utilization -file adder_display_utilization_synth.rpt -pb adder_display_utilization_synth.pb }
