# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory
set_property part xc7a200tfbg676-2 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/sources_1/imports/lcd_module/lcd_module_stub.v
  D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/sources_1/imports/data_ram/data_ram.v
  D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/sources_1/imports/data_ram/data_ram_display.v
}
read_vhdl D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/sources_1/imports/lcd_module/lcd_module_stub.vhdl
read_edif D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/sources_1/imports/lcd_module/lcd_module.edf
read_xdc D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/constrs_1/imports/data_ram/data_ram.xdc
set_property used_in_implementation false [get_files D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.srcs/constrs_1/imports/data_ram/data_ram.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/test/a7/tixijieg/memory/memory_async/data_ram/data_ram.data/wt [current_project]
set_property parent.project_dir D:/test/a7/tixijieg/memory/memory_async/data_ram [current_project]
synth_design -top data_ram_display -part xc7a200tfbg676-2
write_checkpoint data_ram_display.dcp
report_utilization -file data_ram_display_utilization_synth.rpt
