# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/innovril/vivado1/8_pipeline_cpu/8_pipeline_cpu/8_pipeline_cpu.cache/wt [current_project]
set_property parent.project_path /home/innovril/vivado1/8_pipeline_cpu/8_pipeline_cpu/8_pipeline_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/innovril/vivado1/8_pipeline_cpu/inst_rom.dcp
set_property used_in_implementation false [get_files /home/innovril/vivado1/8_pipeline_cpu/inst_rom.dcp]
add_files -quiet /home/innovril/vivado1/8_pipeline_cpu/data_ram.dcp
set_property used_in_implementation false [get_files /home/innovril/vivado1/8_pipeline_cpu/data_ram.dcp]
add_files -quiet /home/innovril/vivado1/lcd_module.dcp
set_property used_in_implementation false [get_files /home/innovril/vivado1/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  /home/innovril/vivado1/8_pipeline_cpu/adder.v
  /home/innovril/vivado1/8_pipeline_cpu/alu.v
  /home/innovril/vivado1/8_pipeline_cpu/multiply.v
  /home/innovril/vivado1/8_pipeline_cpu/exe.v
  /home/innovril/vivado1/8_pipeline_cpu/wb.v
  /home/innovril/vivado1/8_pipeline_cpu/fetch.v
  /home/innovril/vivado1/8_pipeline_cpu/decode.v
  /home/innovril/vivado1/8_pipeline_cpu/mem.v
  /home/innovril/vivado1/8_pipeline_cpu/regfile.v
  /home/innovril/vivado1/8_pipeline_cpu/pipeline_cpu.v
  /home/innovril/vivado1/8_pipeline_cpu/pipeline_cpu_display.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/innovril/vivado1/8_pipeline_cpu/pipeline_cpu.xdc
set_property used_in_implementation false [get_files /home/innovril/vivado1/8_pipeline_cpu/pipeline_cpu.xdc]


synth_design -top pipeline_cpu_display -part xc7a200tfbg676-2


write_checkpoint -force -noxdef pipeline_cpu_display.dcp

catch { report_utilization -file pipeline_cpu_display_utilization_synth.rpt -pb pipeline_cpu_display_utilization_synth.pb }
