# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory
set_property part xc7a200tfbg676-2 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/memory/memory_sync/inst_dcp/inst_rom_stub.v
  D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/lcd_module/lcd_module_stub.v
  D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/inst_rom/inst_rom_display.v
}
read_vhdl {
  D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/memory/memory_sync/inst_dcp/inst_rom_stub.vhdl
  D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/lcd_module/lcd_module_stub.vhdl
}
read_edif D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/memory/memory_sync/inst_dcp/inst_rom.edf
read_edif D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/sources_1/imports/tixijieg/lcd_module/lcd_module.edf
read_xdc D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/constrs_1/imports/inst_rom/inst_rom.xdc
set_property used_in_implementation false [get_files D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.srcs/constrs_1/imports/inst_rom/inst_rom.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/test/a7/tixijieg/memory/memory_sync/inst_rom/inst_rom.data/wt [current_project]
set_property parent.project_dir D:/test/a7/tixijieg/memory/memory_sync/inst_rom [current_project]
synth_design -top inst_rom_display -part xc7a200tfbg676-2
write_checkpoint inst_rom_display.dcp
report_utilization -file inst_rom_display_utilization_synth.rpt
